title: Thomas McDade # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br>
  <a href="https://www.linkedin.com/in/thomas-mcdade-5ba9161b4/">LinkedIn</a> 
  <br>

  
   <a href="/pdf/Thomas.McDade_Resume-UPDATED.pdf" class="btn btn--info">Resume</a>  
  <br>
  
  
  
  <a href="https://github.com/tommymcdade">GitHub</a>  
  <br>

theme: jekyll-theme-minimal
